import test from "node:test";
import assert from "node:assert/strict";
import { loadMigrations } from "../packages/db/src/repository.js";

test("database migrations are ordered and include persistence hardening", async () => {
  const migrations = await loadMigrations();
  assert.deepEqual(migrations.map((migration) => migration.id), ["0001_initial", "0002_persistence_hardening", "0003_ai_evidence_intelligence", "0004_production_file_intelligence", "0005_pilot_readiness_hardening", "0006_data_lifecycle_hardening", "0007_account_recovery", "0008_multi_factor_authentication", "0009_evidence_intelligence_foundation"]);
  assert.match(migrations[0].sql, /CREATE TABLE IF NOT EXISTS audit_packets/);
  assert.match(migrations[1].sql, /selected_rules_pack_id/);
  assert.match(migrations[1].sql, /idx_evidence_org_facility_active_created/);
  assert.match(migrations[2].sql, /CREATE TABLE IF NOT EXISTS evidence_ai_analyses/);
  assert.match(migrations[2].sql, /idx_ai_analyses_org_facility_status/);
  assert.match(migrations[3].sql, /CREATE TABLE IF NOT EXISTS evidence_processing_jobs/);
  assert.match(migrations[3].sql, /idx_processing_jobs_one_active_per_evidence/);
  assert.match(migrations[3].sql, /idx_ai_analyses_current_evidence/);
  assert.match(migrations[4].sql, /lease_expires_at/);
  assert.match(migrations[4].sql, /dead_letter/);
  assert.match(migrations[4].sql, /deleted_by_user_id/);
  assert.match(migrations[5].sql, /legal_hold_active/);
  assert.match(migrations[5].sql, /restored_by_user_id/);
  assert.match(migrations[5].sql, /storage_deletion_retry_count/);
  assert.match(migrations[5].sql, /idx_evidence_retention_due/);
  assert.match(migrations[5].sql, /idx_packets_storage_deletion_failed/);
  assert.match(migrations[6].sql, /CREATE TABLE IF NOT EXISTS password_reset_tokens/);
  assert.match(migrations[6].sql, /token_hash TEXT NOT NULL UNIQUE/);
  assert.match(migrations[6].sql, /idx_password_reset_tokens_user_active/);
  assert.match(migrations[7].sql, /CREATE TABLE IF NOT EXISTS user_mfa_settings/);
  assert.match(migrations[7].sql, /CREATE TABLE IF NOT EXISTS mfa_login_challenges/);
  assert.match(migrations[7].sql, /challenge_token_hash TEXT NOT NULL UNIQUE/);
  assert.match(migrations[7].sql, /CREATE TABLE IF NOT EXISTS mfa_recovery_codes/);
  assert.match(migrations[7].sql, /code_hash TEXT NOT NULL UNIQUE/);
  assert.doesNotMatch(migrations[7].sql, /DROP TABLE|DROP COLUMN|TRUNCATE|ALTER TABLE .* DROP|ALTER TABLE .* RENAME/i);
  assert.match(migrations[8].sql, /normalized_text/);
  assert.match(migrations[8].sql, /provenance_anchors/);
  assert.match(migrations[8].sql, /deterministic_profile/);
  assert.doesNotMatch(migrations[8].sql, /DROP TABLE|DROP COLUMN|TRUNCATE|ALTER TABLE .* DROP|ALTER TABLE .* RENAME/i);
});
